### ISSUE TITLE
Saving Dropbox token in app

### ISSUE THREAD

**Issue by LiisiMotsharg** [marinan87/smartsafe#58]
Right now dropbox token is not saved anywhere.
User is asked to grant permission for app to access it's own folder every time app make a request to Dropbox.

**Comment by lasertunguus** [comment]
In master as of b220b14dca4d182417116ff504d921f5b82a9fe0.

Now will check oauth.json file for token:
- uses the data in the file
- otherwise the usual OAuth procedure is triggered

For future improvements, re-authentication should be done when:
- the oauth.json token is not working
- app is invalidated (maybe the token will be invalidated then as well, making it the same as previous point)
